# Prepare new molecules from sampled binary data

In [4]:
import sys
import joblib
import numpy as np
sys.path.append("../lib/")
sys.path.append("../REINVENT/lib/")
from reinvent_wrapper import run_reinvent,run_reinvent_parallel

In [19]:
n_parallel=2
def run_drl(try_fp_list,project_code):
    try_fp_list=try_fp_list[:,:512]
    integ_df=run_reinvent_parallel(try_fp_list, 
                                   rein_dir='../REINVENT/',
                                   original_dir='../3_2_anneal_comparison/',
                                   n_parallel=n_parallel,
                                   gpu_num=2)
    joblib.dump(integ_df,"data/"+project_code+".bin")
    return integ_df

In [20]:
#gpumcmc10

path="data/mcmc_c1.bin"
res=joblib.load(path)[0]
res[:3]

[array([0., 0., 0., ..., 1., 1., 1.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 1., 1., 0.])]

In [21]:
#convert to int array
try_fp_list=np.array(res,dtype=int)[-1].reshape(1,-1)
try_fp_list=np.array(res,dtype=int)[-30:,:]
try_fp_list

array([[0, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 1],
       ...,
       [0, 0, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 0]])

In [22]:
#run DRL
project_code="mcmc_c1"
run_drl(try_fp_list,project_code)

gpus attributed:  [0, 1]


SMILES  Score  PriorLogP
0       CC(C)=CC=Cc1cccc(C(F)(F)F)c1   0.18     -20.32
1      C=CC(Cc1ccc(F)cc1)c1ccc(F)cc1   0.18     -21.16
2       CC(F)c1ccc(C(=O)C(F)(F)F)cc1   0.17     -23.20
4            CCSC(C)c1ccccc1C(F)(F)F   0.16     -23.32
5            FC(F)([Y])c1ccc([Y])cc1   0.16     -14.41
0                Cc1cccc(C(F)(F)F)c1   0.26     -14.53
1  Cc1cccc(CC=Cc2ccc(C(F)(F)F)cc2)c1   0.23     -23.15
2           O=C(O)c1ccc(C(F)(F)F)cc1   0.22     -15.10
3    Cc1ccccc1C(CCC)c1ccccc1C(F)(F)F   0.21     -29.59
4                N#Cc1cnccc1C(F)(F)F   0.21     -19.08